name: ABot Feature Test Execution

on:
  workflow_dispatch:

jobs:
  run-abot-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=$HOME/.npm-global/bin:$PATH
          npm install -g newman
          npm install -g newman-reporter-html
          echo "PATH=$HOME/.npm-global/bin:$PATH" >> $GITHUB_ENV


      - name: Run ABot Postman Collection
        run: |
          newman run ABot_API_Fixed.postman_collection.json \
            --environment ABot_ENV.postman_environment.json \
            --reporters cli,html,json \
            --reporter-html-export abot-report.html \
            --reporter-json-export abot-report.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: abot-html-report
          path: abot-report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: abot-json-report
          path: abot-report.json
